project:
  type: book

book:
  title: "Introduction to Computational Finance and Financial Econometrics with R"
  author: "Eric Zivot"
  date: last-modified
  chapters:
    - index.qmd
    - 01-ReturnCalculations-new.qmd
    - 02-probReview-new.qmd
    - 03-matrixReview-new.qmd
    - 04-timeSeriesConcepts-new.qmd
    - 05-descriptiveStatistics-new.qmd
    - 06-GWNModel-new.qmd
    - 07-GWNModelEstimation-new.qmd
    - 08-bootstrap-new.qmd
    - 09-hypothesisTestingGWNModel-new.qmd
    - 10-introductionPortfolioTheory-new.qmd
    - 11-PortfolioTheoryMatrix-new.qmd
    - 12-portfolioTheoryNoShortSales-new.qmd
    - references.qmd

bibliography: [book.bib, packages.bib]

execute:
  engine: knitr
  message: false
  warning: false
  fig-show: hold

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

format:
  html:
    theme: cosmo
    page-navigation: true
    code-fold: show
  pdf:
    documentclass: scrreprt
    fontsize: 11pt
    geometry: margin=1in
    linestretch: 1.2
    

editor: source

