# Preface {.unnumbered}

I am a Professor of Economics at the University of Washington (UW) where I teach the class *Introductional to Computational Finance and Financial Econometrics* (ECON 424). This course started as an experiment. In the winter quarter of 1998 I was on leave visiting the economics department at the University of California Los Angeles (UCLA). To help pay for my leave I, I arranged to teach a standard undergraduate econometrics course. My research at the time was moving toward financial econometrics and I thought it would be fun to teach an econometrics course with most of the examples motivated by financial applications. I thought that combining econometrics and statistics topics with financial applications would be a very effective and popular way of getting students interested in learning and applying econometrics. My intuition was right. My students at UCLA loved the version of the course I offered. After returning to the University of Washington, I created the upper division undergraduate course *Introduction to Computational and Financial Econometrics*. The course was an immediate hit. This book evolved from my lecture notes for the course.

*Who is the book written for? What background is required?*

My ECON 424 course is taken mainly by senior economics majors who are pursuing the more quantitative Bachelor of Science Degree in Economics at UW. These students typically have at least one year of calculus, intermediate microeconomics with some calculus (so they are exposed to optimization under constraints using Lagrange multipliers), and an introductory course in probability and statistics for economics majors. Some students have taken a course in linear algebra, some have taken an introductory econometrics course, and some have taken a financial economics course. I find that the typical introductory probability and statistics course is at a lower level than is needed for much of the material in my course. Ideally, students should have an intermediate probability and statistics course that uses calculus[^index-1]. As a result, I spend a week at the beginning of the course doing a review of random variables and probability that uses basic calculus. A key part of the review is the manipulation of random variables, computing expectations of functions of random variables, etc., so that the students have the necessary tools to work with simple probabilistic models for asset returns. After the review of probability theory I introduce some basic time series concepts (e.g., stochastic processes and stationarity), as these concepts are often not taught in introductory probability and statistics classes, and I also do a quick review of basic matrix algebra that I use throughout the course. The use of matrix algebra is important for two reasons. First, most introductory textbook treatments of portfolio theory show calculations for the simple case of two assets and then talk about how the calculations extend to the general case of many assets but do not show how this is done. Hence, students are not capable of implementing the theory for real world portfolios. I emphasize that with knowledge of just a little bit of matrix algebra - essentially matrix addition, multiplication, inversion, and some matrix differential calculus - the general analysis of portfolio theory can be easily learned and implemented. Second, R is a vectorized and matrix programming language and so basic knowledge of matrix algebra allows students to easily understand and implement the R code for portfolio analysis.

[^index-1]: Insert reference to recent MIT Press book here

*Main topics covered in the book*

After the review material, I jump into descriptive statistical analysis of historical financial time series data. I emphasize that my approach to building models for asset returns is based on first looking at the historical data and studying its properties. I start by telling students to pretend that observed returns on assets are realizations from some unknown covariance stationary stochastic process. I review common graphical and numerical descriptive statistics (e.g., histograms, QQ-plots, sample mean, variance, correlation, etc.). The goal of descriptive statistical analysis is to compile a collection of “stylized facts” that can be used as building blocks for probabilistic models for asset returns. For example, I show that monthly asset returns are typically uncorrelated over time, have empirical distributions (histograms) that look like normal bell curves, have means close to zero, are positively correlated with other assets, etc. I also emphasize that some “stylized facts” of asset returns appear to stay the same for different investment horizons (daily, weekly, and monthly returns are uncorrelated) and some do not (e.g., daily and weekly returns have fatter tails than the normal and show evidence of nonlinear time dependence in higher moments)

*Why us R?*

My early versions of *Introduction to Computational and Financial Econometrics* used Microsoft Excel as the main software tool as R was not yet around then. My decision to use Excel was for the students' benefit. Students having experience with Excel was, and still is, in high demand by employers in the finance industry. It is often said, "the financial world runs out of an Excel spreadsheet". However, Excel is not a good tool for doing statistics. Even though you *can* do statistical analysis in Excel, does not mean that you *should* do statistical analysis in Excel. I searched for Excel add-ins to make doing statistical analysis in Excel easier but I did not like what was available. Everything changed when I met Professor Doug Martin from the UW statistics department. Doug founded the company who created S-PLUS, the commercial version of the S statistical programming language developed by John Chambers at Bell Labs (R became the open source version of S in 2000). S is a beautiful language for exploratory data and statistical analysis and S-PLUS made it easily available to students on windows PCs. In the early 2000s I used Excel together with S-PLUS for my course. This hybrid approach worked well but the difficulties of getting student licenses at the beginning of the quarter was always a headache. As R matured in the mid to late 2000s, I made the switch from S-PLUS to R and never looked back. As the course evolved and R became more commonly used in the financial world, and Rstudio became the integrated developer environment of choice for R, I eventually dropped the use of Excel and focused solely on R for the applications and examples in the book.

Many economics students lack experience with programming languages and some find R a difficult language to learn and use. My approach to dealing with this reality is to provide all of the R code to do calculations in the class lectures, in the textbook examples, and on homework assignments. In this way students do not have to worry about the coding aspect of the class and can more easily concentrate on the concepts of computational finance and financial econometrics. I find that students learn to use R quite well this way – learning by doing – and most students are quite proficient in R by the end of the course.

There are a lot of free resources on the web for learning R. In my Coursera course I partnered with DataCamp to provide a web-based learning environment for R tailored to the course material. I have found that this has substantially lowered the learning curve for many students. Student mostly use either a MAC or PC for their work (a few geeks use UNIX). I found that some things didn’t always work well across platforms (usually issues with the file system). In 2014, I required students to use Rstudio as the environment for using R. This makes learning and working with R even easier. Another advantage of using Rstudio is that my lecture notes and homework assignments are be created using Rmarkdown.

*Longer print book*

(Shorter ebook). This book is based on my University of Washington sponsored Coursera course Introduction to Computational Finance and Financial Econometrics that has been running every quarter on Coursera since 2013. This Coursera course is based on the Summer 2013 offering of my University of Washington advanced undergraduate economics course of the same name. At the time, my UW course was part of a three course summer certificate in Fundamentals of Quantitative Finance offered by the Professional Masters Program in Computational Finance & Risk Management that was video-recorded and available for online students. An edited version of this course became the Coursera course. The popularity of the course encouraged me to convert the class notes for the course into a short book.

The book was typeset using Lyx with all of the R code examples embedded into the document and evaluated using knitr. I am extremely grateful to Yihui Xie for writing his wonderful book Dynamics Documents with R and knitr as this book would not have been possible without it. I am a firm believer in the “reproducible research paradigm”.

The book's accompanying R package `introcompfinr` contains all of the financial data used for the examples presented in the book as well as a number of R functions written by me for estimating some simple models of asset returns, and doing portfolio and risk analysis. The package is freely available on GitHub at https://github.com/ezivot/introcompfinr and can be installed using:

```{r}
#| eval: false 
install.packages("pak")
pak::pak("ezivot/introcompfinr").
```

*How is this book different from other introductory book on financial econometrics?*

There are now many good books written on the topic of computational/quantitative finance and financial econometrics with examples in R at various levels of sophistication. Books written for advanced U.S. undergraduates include Carmona (2014) and Tsay (2012). Books written for Masters students in computational finance or financial engineering courses include Fan and Yao (20xx), Lai and Xing (2008), Ruppert and Matteson (2015) and Tsay (2010). All of these books assume the readers have a broader mathematical and statistical background than what I assume here. Hence, this book is truly an “introduction” to the methods of computational finance and financial econometrics and is appropriate for undergraduate economics and finance majors at Universities worldwide. Another feature that distinguishes this book from others is the extensive use of R and illustrated R code throughout the book. In this regard, this book is a “hands on” book in which the student can readily execute the R examples on their own computer while reading the book. This allows the student to also learn R as well as the concepts in the book.

::: {style="text-align: right;"}
Eric Zivot\
Seattle, Washington\
August 2026
:::

# Acknowledgments {.unnumbered}

Many people have helped with the development of this book. First and foremost, I would like to thank the students at UW who have taken my course over the last fifteen years. I have received countless comments, corrections, and suggestions that have greatly improved the exposition and material in the book.

A lot of how I think about the statistical analysis of financial data has been shaped by many discussions and interactions with my long-term colleague and good friend R. Douglas Martin. Doug introduced me to the S language and I had the pleasure of working with him at Insightful where we developed the S+FinMetrics module for S-PLUS and I wrote the book *Modeling Financial Time Series with S-PLUS* with my former Ph.D. student Jiahui (Jeffrey) Wang.

My very patient wife Nina Sidneva carefully proof-read many early versions of the chapters as they were under development and caught many of my stupid errors. Xiao Yin proof-read most of the chapters after I converted my Latex notes to Lyx and incorporated the R examples with `knitr`. I could not have written the book without the expert technical help from Bethany Yollin and the wonderful book *Dynamics Documents with R and knitr* by Yihui Xie. Bethany helped with the conversion of my Latex notes to Lyx and the incorporation of the R examples in the text using `knitr`. She also helped to develop and maintain an early version the book's R package, `IntroCompfinR`. Any problem I found with Lyx and `knitr` was solved by referring to Yihui’s book. In 2020 I decided to migrate the book from Lyx to Rmarkdown so that everything could be managed within Rstudio and the book could be generated using `bookdown`. My UW PhD RAs Yumming (Herbert) Liu, Pushpak Sarkar and Kovid Puria made this happen. In 2026, I moved from `bookdown` to Quarto.

My interactions with the R community, especially those involved with R/Finance, have been invaluable for learning and using R for the analysis of financial data. In particular, Brian Peterson and Peter Carl have been incredibly helpful and supportive of my book projects. I use their wonderful R package `PerformanceAnalytics` throughout the book. Working with time series data is made so much easier with Achiem Zieles’ `zoo` package and Jeff Ryan’s `xts` package. Many University of Washington (UW) econ PhD students (Brian Donhauser, Ming He, Wan-Jung Hsu, Kara Ng, Anthony Sanford, Galib Sultan, Cindy Huang) acted as TAs for my undergraduate course and gave constructive feedback. I also thank Coursera for helping me convert my undergraduate course into Coursera format.
